### PR TITLE
handle response and data separately

### PR DESCRIPTION
**Pull request by tvanier**
**Proposal**: Handle all get and post responses through a single `handleResponse` helper function, which returns an object with a `response` property, and optional `data`, can easily be [destructured](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring):
```javascript
// just the fetch response
const { response } = await get`http://example.com/ping`;
if (response.ok) {
  console.log('ping sucess!');
}
```
with data:
```javascript
const { response, data } = await get`http://example.com/something`;
if (response.ok) {
  console.log('got something', data);
}
```

### CODE REVIEW

**Comment by valqelyan** [comment]
thank you for your PL. I will review later

**Comment by tvanier** [comment]
Thanks @vaheqelyan !
I really like the idea of "fetching with strings". I was thinking of preparing another PR to use [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) and have a single `get.js`, `post.js` and `index.js` (no browser/node distinction). Could that work?

**Comment by valqelyan** [comment]
@tvanier As I know, isomorphic-fetch is just a polyfill?. See this https://github.com/vaheqelyan/karin/issues/2.

**Comment by valqelyan** [comment]
I think it would be better if this library used Axios instead of Fetch API

**Pull request merged**
